apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"my-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"manual","volumeMode":"Filesystem","volumeName":"my-pv"}}
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2023-11-21T05:26:22Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: my-pvc
  namespace: default
  resourceVersion: "2040701"
  uid: 6d29f24d-337a-40df-9ea9-fe6fc24216e5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: my-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
