apiVersion: apps/v1
kind: StatefulSet 
metadata:
  annotations:
  labels:
    app: slurmd
  name: slurmd
  
spec:
  replicas: 3
  serviceName: slurmd-headless
  selector:
    matchLabels:
      app: slurmd
  template:
    metadata:
      labels:
        app: slurmd
    spec:
      containers:
      - image: rancavil/slurm-node:19.05.5-1
        env:
        - name: SLURM_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: IfNotPresent
        name: slurm-node
        resources: {}
        volumeMounts:
        - mountPath: /home/admin
          name: shared-vol
        - name: slurm-config
          mountPath: /etc/slurm-llnl/slurm.conf
          subPath: slurm.conf
      volumes:
      - name: shared-vol
        persistentVolumeClaim:
          claimName: my-pvc
      - name: slurm-config
        configMap:
          name:  slurmconf
      dnsConfig:
        searches:
        - slurmd-headless.slurm2.svc.cluster.local 
      dnsPolicy: ClusterFirst
