apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: slurmmaster
  name: slurmmaster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmmaster
  template:
    metadata:
      labels:
        app: slurmmaster
    spec:
      hostname: slurmmaster
      containers:
      - image: rancavil/slurm-master:19.05.5-1
        imagePullPolicy: IfNotPresent
        name: slurm-master
        resources: {}
        volumeMounts:
        - mountPath: /home/admin
          name: shared-vol
        - name: slurm-config
          mountPath: /etc/slurm-llnl/slurm.conf
          subPath: slurm.conf
      volumes:
      - name: shared-vol
        persistentVolumeClaim:
          claimName: my-pvc
      - name: slurm-config
        configMap:
          name:  slurmconf
