apiVersion: v1
kind: Service
metadata:
  labels:
    app: slurmmaster
  name: slurmmaster
spec:
  ports:
  - port: 3306
    name: tcp-1
    protocol: TCP
    targetPort: 3306
  - port: 6817
    name: tcp-2
    protocol: TCP
    targetPort: 6817
  - port: 6818
    name: tcp-3
    protocol: TCP
    targetPort: 6818
  - port: 6819
    name: tcp-4
    protocol: TCP
    targetPort: 6819
  selector:
    app: slurmmaster
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slurmd
  name: slurmd-headless
spec:
  clusterIP: None
  ports:
  - port: 6818
    protocol: TCP
    targetPort: 6818
  selector:
    app: slurmd
  type: ClusterIP


